### ISSUE TITLE
Internal Server Error returned when running query

### ISSUE THREAD

**Issue by sylviawangfr** [dbpedia/lookup-application#16]
I followed the described steps of using pre-build index. When I run curl http://localhost:9273/lookup-application/api/search?query=Berlin
I got this error message:
HTTP Status 500 – Internal Server Error
Exception Report
Description
The server encountered an unexpected condition that prevented it from fulfilling the request.
Exception java.lang.NullPointerException
	org.dbpedia.lookup.LookupServlet.doPostOrGet(LookupServlet.java:108)
	org.dbpedia.lookup.LookupServlet.doGet(LookupServlet.java:85)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
The full stack trace of the root cause is available in the server logs.
Apache Tomcat/9.0.35

Steps to reproduce:
1. use pre-build index and change docker-compose.yml
2. docker-compose up -d
3. curl http://localhost:9273/lookup-application/api/search?query=Berlin

My attempts to investigate:
1. exec to the container and check the tomcat log, same error in log file
2. curl http://localhost:9273/lookup-application/ return a hello world page which is as expected.
3. build my own image and run same curl commands, got error: "Recv failure: Connection reset by peer"

**Comment by sylviawangfr** [comment]
I fixed it, will raise a PR

**Comment by sebnapi** [comment]
Hey! Just run into the same issue.

Could you share your investigation of the result?

Thank you a lot!

**Comment by holycrab13** [comment]
Hi, I was able to reproduce the issue. The stacktrace is a bit misleading since the error happens in the servlet initialization. The 'catalina.out' inside of the docker logged that it was unable to find the pre-built index. A similar error will now be thrown when making get requests instead of the misleading one.
The docker compose volume is set up incorrectly in the example file, sending the files to ```/root/lucene-index``` while the app-config states that the index should be found at ```/root/index```. Changing the docker-compose to send the files to ```/root/index``` fixes the issue.

Also make sure that the downloaded pre-built index is *extracted* in that folder.

Again, whatever went wrong should be clearer in the future with the updated exception

**Comment by sebnapi** [comment]
Holy Crab! That was fast. Thank you ;)
